name: HytaleScoreboardTest
main: com.example.hytale.scoreboard.MainPlugin
version: 1.0.0
description: Scoreboard sidebar test with placeholders
author: Example
commands:
  scoreboard:
    description: Gère l'affichage du scoreboard
    usage: /scoreboard <on|off|test|reload>
    aliases: [sb]
